defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - tqdm_progress_bar.yaml
  - rollout_evaluation.yaml
  - _self_

model_checkpoint:
  monitor: "val/success_once_rate" # name of the logged metric which determines when model is improving
  mode: "max" # "max" means higher metric value is better, can be also "min"
  save_top_k: 3 # save k best models (determined by above metric)
  save_last: true # additionally always save model from last epoch
  verbose: false
  dirpath: "${hydra:runtime.output_dir}/checkpoints"
  filename: "step_{step:06d}"
  auto_insert_metric_name: false

early_stopping:
  monitor: "val/loss"
  mode: "min"
  patience: 10 # "Stop training if the monitored metric (val/success_rate) doesn't improve after 10 consecutive validation checks"
  min_delta: 1e-5 # minimum change in the monitored quantity to qualify as an improvement

model_summary:
  max_depth: 2

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor

device_utilisation:
  _target_: lightning.pytorch.callbacks.DeviceStatsMonitor

throughput:
  _target_: policy.algorithms.callbacks.samples_per_second.MeasureSamplesPerSecondCallback
