rollout_evaluation:
  _target_: policy.algorithms.callbacks.rollout_evaluation.RolloutEvaluationCallback
  _recursive_: false
  permuter: null
  num_val_episodes: 10
  num_test_episodes: 100
  max_episode_steps: 200
  num_envs: null # = 1 will lead CPU backend, >1 will lead to GPU, null will let the system automatically set it
  ignore_terminations: true
  clamp_action: true
  video_dir: null
  seed: ${seed} # Seed is passed by config.py
