_target_: policy.datamodules.adapter_datamodule.AdapterDataModule
batch_size: 256
num_workers: 4
pin_memory: true

base_datamodule:
  _target_: policy.datamodules.maniskill_datamodule.ManiSkillDataModule
  # TODO: unfortunately PlaceSphere do NOT have demos, so I should craft them
  dataset_file: ???
  seed: ${seed}

adapter:
  _target_: ???
