_target_: policy.datamodules.aligned_states_datamodule.AlignedStatesDataModule
batch_size: 256
num_workers: 4

base_datamodule:
  _target_: policy.datamodules.trajectory_datamodule.TrajectoryDataModule
  dataset_file: ???
  seed: ${seed}

adapter:
  _target_: ???
