_target_: policy.datamodules.maniskill_datamodule.ManiSkillDataModule
dataset_file: ${oc.env:HOME}/.maniskill/demos/StackCube-v1/motionplanning/trajectory.h5
cond_source: "obs"
cond_horizon: 2
pred_horizon: 16
batch_size: 128
num_workers: 4
val_split: 0.1
seed: none
