_target_: policy.datamodules.translator_datamodule.TranslatorDataModule
batch_size: 256
num_workers: 4

base_datamodule:
  _target_: policy.datamodules.maniskill_datamodule.ManiSkillDataModule
  dataset_file: ???
  seed: ${seed}

adapter:
  _target_: ???
