defaults:
  - network: diffusion_gpt
  - optimizer: AdamW
  - ema: default
  - noise_scheduler: null
  - lr_scheduler: cosine_with_warmup
  - normalizer@obs_normalizer: z_score
  - normalizer@act_normalizer: min_max

_target_: policy.algorithms.beso_policy.BesoPolicy
_recursive_: false

obs_horizon: ${datamodule.obs_horizon}
pred_horizon: ${datamodule.pred_horizon}
act_horizon: ??

obs_dim: ${datamodule.obs_dim}
act_dim: ${datamodule.act_dim}

# Training: Log-logistic parameters
alpha: 0.5
beta: 0.5

# Inference: Continuous-DDIM
sigma_max: 1.0
sigma_min: 0.005

# Karras scaling
sigma_data: 0.5

pred_last_action_only: false

goal_horizon: 1
use_proprio_token: false
num_parallel_samples: 1
goal_drop_prob: 0.0
cfg_lambda: 0.0

network:
  act_dim: ${..act_dim}
  obs_horizon: ${..obs_horizon}
  pred_horizon: ${..pred_horizon}
  goal_horizon: ${..goal_horizon}
  use_proprio_token: ${..use_proprio_token}

optimizer:
  lr: 1e-4
  weight_decay: 1e-5
  betas: [0.9, 0.95]

lr_scheduler:
  num_training_steps: ${trainer.max_steps}
