defaults:
  - network: diffusion_gpt
  - noise_scheduler: null
  - ema: default
  - optimizer: AdamW
  - lr_scheduler: cosine_with_warmup
  - normalizer: z_score

_target_: policy.algorithms.beso_policy.BesoPolicy
_recursive_: false

obs_horizon: ${datamodule.obs_horizon}
pred_horizon: ${datamodule.pred_horizon}
act_horizon: ??

obs_dim: ${datamodule.obs_dim}
act_dim: ${datamodule.act_dim}

# Training: Log-logistic parameters
alpha: 0.5
beta: 0.5

# Inference: Continuous-DDIM
sigma_max: 1.0
sigma_min: 0.005

# Karras scaling
sigma_data: 0.5

pred_last_action_only: false

network:
  act_dim: ${..act_dim}
  external_cond_horizon: ${..obs_horizon}
  pred_horizon: ${..pred_horizon}

optimizer:
  lr: 1e-4
  weight_decay: 1e-5
  betas: [0.9, 0.95]

lr_scheduler:
  num_training_steps: ${trainer.max_steps}

action_normalizer: null
