defaults:
    - network: unet1d
    - optimizer: adam # Assuming you have an optimizer config folder like the template

_target_: policy.algorithms.diffusion.DiffusionPolicy

# obs_horizon and pred_horizon are automatically fetched by datamodule
act_horizon: 8
action_dim: 8
obs_dim: 13

num_diffusion_iters: 100
lr: 1e-4
warmup_steps: 500
init_seed: 42

# You can eventually override unet1d and adam down below. e.g.:
# network:
#   down_dims: [128, 256, 512]  # Changes just the dims, keeps kernel_size etc. from unet1d.yaml

# optimizer:
#   weight_decay: 1e-5          # Overrides the weight decay in adam.yaml
