defaults:
  - network: unet1d
  - noise_scheduler: ddpm
  - ema: default
  - optimizer: AdamW
  - lr_scheduler: cosine_with_warmup

_target_: policy.algorithms.diffusion_policy.DiffusionPolicy
_recursive_: false # Since we instantiate the network and optimizer inside the algorithm, we prevent hydra from trying to instantiate them before

obs_horizon: ${datamodule.obs_horizon}
pred_horizon: ${datamodule.pred_horizon}
act_horizon: 8

obs_dim: ${datamodule.obs_dim}
act_dim: ${datamodule.act_dim}

optimizer:
  lr: 1e-4
  weight_decay: 1e-5

lr_scheduler:
  num_training_steps: ${trainer.max_steps}
