defaults:
  - network: unet1d
  - noise_scheduler: ddpm
  - ema: default
  - optimizer: AdamW
  - lr_scheduler: cosine_with_warmup
  - _self_

_target_: policy.algorithms.diffusion.DiffusionPolicy
_recursive_: false # Since we instantiate the network and optimizer inside the algorithm, we prevent hydra from trying to instantiate them before

act_horizon: 8

lr_scheduler:
  num_training_steps: ${trainer.max_steps}
