defaults:
  - diffusion_policy
  - embedder@encoder.embedder: null
  - pooling@encoder.pooling: null

_target_: policy.algorithms.goal_conditioned_diffusion_policy.GoalConditionedDiffusionPolicy

goal_horizon: 1
relative_goal: true
