_target_: policy.algorithms.mlp_adapter.MLPAdapter
_recursive_: false

defaults:
  - network: mlp
  - optimizer: AdamW
  - lr_scheduler: StepLR

# TODO: maybe something more clean?
loss_mask_indices:
  [
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
  ]

optimizer:
  lr: 1e-3
