_target_: policy.algorithms.mlp_adapter.MLPAdapter
_recursive_: false

defaults:
  - network: mlp
  - optimizer: AdamW
  - lr_scheduler: StepLR

lr_scheduler:
  step_size: 500 # batch-wise, not epochs

optimizer:
  lr: 1e-3
  weight_decay: 1e-4
