_target_: policy.algorithms.multi_task_state_aligner.MultiTaskStateAligner
_recursive_: false

defaults:
  - network: conditioned_linear
  - optimizer: Adam
  - lr_scheduler: null

# TODO: should num/dict of tasks be fetched from the datamodule?

task_mapping:
  PlaceSphereWristcam-v1: 0
  StackCubeSwapped-v1: 1

network:
  num_conditions: 2 # Must match the above

optimizer:
  lr: 1e-3
