_target_: policy.algorithms.multi_task_state_aligner.MultiTaskStateAligner
_recursive_: false

defaults:
  - network: task_conditioned_mlp
  - optimizer: Adam
  - lr_scheduler: null

task_mapping:
  # TODO: should be fetched from the datamodule?
  PlaceSphereWristcam-v1: 0
  StackCubeSwapped-v1: 1

optimizer:
  lr: 1e-3
