_target_: policy.algorithms.multitask_state_translator.MultiTaskStateTranslator
_recursive_: false

defaults:
  - network: task_conditioned_mlp
  - optimizer: Adam
  - lr_scheduler: null

optimizer:
  lr: 1e-3
