_target_: policy.algorithms.multi_task_state_aligner.MultiTaskStateAligner
_recursive_: false

defaults:
  - network: task_conditioned_mlp
  - optimizer: Adam
  - lr_scheduler: null

task_mapping:
  PlaceSphere-v1: 0
  PlaceSphereWristcam-v1: 1
  StackCube-v1: 2
  StackCubeSwapped-v1: 3

optimizer:
  lr: 1e-3
